services:
  tutorial-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GEMINI_API_KEY: <your_gemini_api_key>
    volumes:
      - ./output:/app
    command: ["main","--repo", "https://github.com/username/repo-name", "--exclude", "*.md"]